Big/ElibreBundle/Entity/Document.php
<?php

namespace Big\ElibreBundle\Entity;

use Big\ElibreBundle\Model\FileIcon;
use Doctrine\ORM\Mapping as ORM;

/**
 * @author Alexander Glumoff <glumoff at gmail.com>
 */

/**
 * Document
 *
 * @ORM\Table(name="documents")
 * @ORM\Entity
 */
class Document {

  /**
   * @ORM\Column(name="id", type="integer")
   * @ORM\Id
   * @ORM\GeneratedValue(strategy="AUTO")
   */
  private $id;

  /**
   * @ORM\Column(name="path", type="text")
   */
  private $path;

  /**
   * @ORM\Column(name="title", type="string", length=100)
   */
  private $title;

//    create_dt	datetime
//    edit_dt		datetime
//    annotation	text
//    tags		varchar(200)
//    theme_id	int(11)

  /**
   * @ORM\Column(name="create_dt", type="datetime")
   */
  private $create_dt;

  /**
   * @ORM\Column(name="edit_dt", type="datetime")
   */
  private $edit_dt;

  /**
   * @ORM\Column(name="annotation", type="text", nullable=TRUE)
   */
  private $annotation;

  /**
   * @ORM\Column(name="tags", type="string", length=200)
   */
  private $tags;
  private $fileType;

  /**
   * @ORM\Column(name="mimetype", type="string", length=100, nullable=TRUE)
   */
  private $mimeType;

  /**
   * @ORM\Column(name="picture", type="blob", nullable=TRUE)
   */
  private $picture;

  /**
   * @ORM\Column(name="pic_mimetype", type="string", length=100, nullable=TRUE)
   */
  private $pictureMimeType;

  /**
   *
   * @var FileIcon
   */
  private $icon;

  /**
   * @ORM\ManyToOne(targetEntity="Theme")
   * @ORM\JoinColumn(name="theme_id", referencedColumnName="id")
   */
  private $theme;

  /**
   *
   * @param array $arr
   */
  public function __construct($arr = NULL) {
    if (isset($arr)) {
      $this->fillFromArray($arr);
    }
  }

  protected function fillFromArray($arr) {
    if (is_array($arr)) {
      if (isset($arr['id']))
        $this->id = $arr['id'];
      if (isset($arr['path']))
        $this->path = $arr['path'];
      if (isset($arr['title']))
        $this->title = $arr['title'];
      if (isset($arr['create_dt']))
        $this->create_dt = $arr['create_dt'];
      if (isset($arr['edit_dt']))
        $this->edit_dt = $arr['edit_dt'];
      if (isset($arr['annotation']))
        $this->annotation = $arr['annotation'];
      if (isset($arr['tags']))
        $this->tags = $arr['tags'];
      if (isset($arr['theme_id']))
        $this->theme_id = $arr['theme_id'];
    }
  }

  public function getPath() {
    return $this->path;
  }

  public function getTitle() {
    return $this->title;
  }

  public function getAnnotation() {
    return $this->annotation;
  }

  public function getMimeType() {
    return $this->mimeType;
  }

  public function getPictureMimeType() {
    return $this->pictureMimeType;
  }

  public function getPicture() {
    return $this->picture;
  }

  public function getPictureBase64() {
    return base64_encode(stream_get_contents($this->picture));
  }

  public function setMimeType($mtype) {
    $this->mimeType = $mtype;
    return $this;
  }

  public function setPictureMimeType($mtype) {
    $this->pictureMimeType = $mtype;
    return $this;
  }

  public function setPicture($picture) {
    $this->picture = $picture;
    return $this;
  }

//  public function getMimeType() {
//    if (!isset($this->mimeType)) {
//      $finfo = finfo_open(FILEINFO_MIME_TYPE);
//      $this->mimeType = finfo_file($finfo, $this->path);
//      finfo_close($finfo);
//    }
//    return $this->mimeType;
//  }

  public function getFileType() {
    if (!isset($this->fileType)) {
      $this->fileType = pathinfo($this->path, PATHINFO_EXTENSION);
    }
    return $this->fileType;
  }

  public function getIcon() {
    if (!isset($this->icon)) {
      $this->icon = new FileIcon(strtolower($this->getFileType()));
//      $this->icon = new FileIcon($this->getFileType());
    }
    return $this->icon->getIcon();
  }

//    public function setID($id) {
//        $this->id = $id;
//    }

  public function setPath($path) {
    $this->path = $path;
  }

  public function setTitle($title) {
    $this->title = $title;
  }

  /**
   * Get id
   *
   * @return integer 
   */
  public function getId() {
    return $this->id;
  }

  public function setId($id) {
    $this->id = $id;

    return $this;
    
  }
  
  /**
   * Set create_dt
   *
   * @param \DateTime $createDt
   * @return Document
   */
  public function setCreateDt($createDt) {
    if (!$createDt) {
      $createDt = time();
    }
    $this->create_dt = $createDt;

    return $this;
  }

  /**
   * Get create_dt
   *
   * @return \DateTime 
   */
  public function getCreateDt() {
    if (!$this->create_dt) {
      $this->setCreateDt(time());
    }
    return $this->create_dt;
  }

  /**
   * Set edit_dt
   *
   * @param \DateTime $editDt
   * @return Document
   */
  public function setEditDt($editDt) {
    if (!$editDt) {
      $editDt = time();
    }
    $this->edit_dt = $editDt;

    return $this;
  }

  /**
   * Get edit_dt
   *
   * @return \DateTime 
   */
  public function getEditDt() {
    if (!$this->edit_dt) {
      $this->setEditDt(time());
    }
    return $this->edit_dt;
  }

  /**
   * Set annotation
   *
   * @param string $annotation
   * @return Document
   */
  public function setAnnotation($annotation) {
    $this->annotation = $annotation;

    return $this;
  }

  /**
   * Set tags
   *
   * @param string $tags
   * @return Document
   */
  public function setTags($tags) {
    $this->tags = $tags;

    return $this;
  }

  /**
   * Get tags
   *
   * @return string 
   */
  public function getTags() {
    return $this->tags;
  }

//  /**
//   * Set theme_id
//   *
//   * @param integer $themeId
//   * @return Document
//   */
//  public function setThemeId($themeId) {
//    $this->theme_id = $themeId;
//
//    return $this;
//  }
//
//  /**
//   * Get theme_id
//   *
//   * @return integer 
//   */
//  public function getThemeId() {
//    return $this->theme_id;
//  }
//

  /**
   * Set theme
   *
   * @param \Big\ElibreBundle\Entity\Theme $theme
   * @return Document
   */
  public function setTheme(\Big\ElibreBundle\Entity\Theme $theme = null) {
    $this->theme = $theme;

    return $this;
  }

  /**
   * Get theme
   *
   * @return \Big\ElibreBundle\Entity\Theme 
   */
  public function getTheme() {
    return $this->theme;
  }

}

Big/ElibreBundle/Controller/DefaultController.php
<?php

namespace Big\ElibreBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Big\ElibreBundle\db\ElibreDBDelegate;

class DefaultController extends Controller {

  protected $templateParams = NULL;

  public function indexAction($page, $action) {
    $this->getTemplateParams();
    $this->templateParams['content'] = $this->getPageContent($page);
    $response = NULL;
    if ($action == 'edit') {
      $response = $this->render('BigElibreBundle:Default:editpage.html.twig', $this->getTemplateParams());
    } elseif ($action == 'view') { // view
      $response = $this->render('BigElibreBundle:Default:index.html.twig', $this->getTemplateParams());
    }
    return $response;
  }

  protected function getTemplateParams() {
    //var_dump($this->get('translator')->getLocale());
//    $this->get('translator')->setLocale($this->getRequest()->getPreferredLanguage());
    //var_dump($this->get('translator')->getLocale());

    if ($this->templateParams === NULL) {
      $this->templateParams = array();
      $this->templateParams['menuThemes'] = $this->getThemesMenuArray();
    }
    $this->templateParams['DIRECTORY_SEPARATOR'] = DIRECTORY_SEPARATOR;
    return $this->templateParams;
  }

  protected function getPageContent($pageName) {
//    $content = "getPageContent($page)";

    if (preg_match("/^[a-z]*$/", $pageName) == 0) {
      $pageName = "home";
    }

    $em = $this->getDoctrine()->getManager();
    $query = $em->createQuery(
                    'SELECT p
                      FROM BigElibreBundle:Page p
                      WHERE p.name = :name
                      ORDER BY p.id DESC'
            )->setParameter('name', $pageName);
    $pages = $query->getResult();

    if (is_array($pages) && (count($pages) > 0)) {
      //$content = var_export($pages, TRUE);
      $request = $this->getRequest();
      $userLang = $request->getLocale();
      //$userLang = $request->getPreferredLanguage();
      $page = NULL;
      foreach ($pages as $curPage) {
        if ($curPage->getLang() == $userLang) {
          $page = $curPage;
          break;
        }
      }
      if (!isset($page)) {
        $page = $pages[0]; // перша ліпша
      }

      $content = $page->getContent();
    } else {
      $content = $this->get('translator')->trans('error.404', array(), 'messages');
    }

    return $content;
  }

  protected function getThemesMenuArray() {
    $db = new ElibreDBDelegate();
    $themesList = $db->getThemes(NULL, $this->getUserRole());
    return $themesList->getThemesArray();
  }

  protected function getUserRole() {
    if (!$this->get('security.context')->isGranted('IS_AUTHENTICATED_FULLY')) {
      return 'IS_AUTHENTICATED_ANONYMOUSLY';
    } else {
      $user = $this->getUser();
      $roles = $user->getRoles();
      return $roles[0];
    }
  }

  /**
   * 
   * @param integer $theme_id
   */
  protected function getThemeFullDirName($theme_id) {
    $dbm = $this->getDoctrine()->getManager();
    $path = '';

    do {
      /* @var $theme Theme */
      $theme = $dbm->getRepository("BigElibreBundle:Theme")->find($theme_id);
      if (!$theme) {
        break;
      }
      $path = DIRECTORY_SEPARATOR . $theme->getDirName() . $path;
      $theme_id = $theme->getParentId();
    } while ($theme_id > 0);

    return $path;
  }
  
}

Big/ElibreBundle/Resources/views/Default/doc.html.twig
{% extends 'BigElibreBundle:Default:index.html.twig' %}

{% block content %}
  {% if doc %}
    <div class="docTitle">
      <a href="{{ path('big_elibre_theme', {'theme_code': doc.theme.code,  'action' : 'view' }) }}">{{ doc.theme.title }}</a> / {{ attribute(doc, 'title') }}
    </div>

    {% if doc.pictureMimeType and doc.picture %}
      <div class="img-thumbnail">
        {#        {{ doc.pictureMimeType }}#}
        {#        {{ doc.picture }}#}
        <img src="data:{{ doc.pictureMimeType }};base64,{{ doc.pictureBase64 }}" />
      </div>
    {% endif %}

    <a class="download" href="{{ path('big_elibre_doc', {'doc_id': doc.id,  'action' : 'open' }) }}" title="{% trans %}doc.open.label{% endtrans %}">
      {% if doc.icon %} 
        <img src="{{ asset('bundles/bigelibre/images/icons/') }}{{ doc.icon }}" class="icon big"/>
      {% else %}
        <img src="{{ asset('bundles/bigelibre/images/down.png') }}" class="big"/>
      {% endif %}
    </a>

    {#    {% if is_granted('ROLE_ADMIN') %}
          <p>
            <b>{% trans %}doc.fullpath.label{% endtrans %}:</b>
          </p>
          <p>
            {{ docFullPathDir|raw }}
          </p>
          <p></p>
        {% endif %}
    #}
    <br/>
    <br/>
    <div>
      <a class="btn btn-warning btn-sm" href="{{ path('big_elibre_doc', {'doc_id': doc.id,  'action' : 'open' }) }}" title="{% trans %}doc.open.label{% endtrans %}">
        <span class="glyphicon glyphicon-open"></span> {% trans %}doc.open.label{% endtrans %}
      </a>
      <a class="btn btn-primary btn-sm" href="{{ path('big_elibre_doc', {'doc_id': doc.id,  'action' : 'download' }) }}" title="{% trans %}doc.download.label{% endtrans %}">
        <span class="glyphicon glyphicon-save"></span> {% trans %}doc.download.label{% endtrans %}
      </a>
    </div>

    <div class="docAnnotation">
      {#<h3>Аннотация:</h3>#}
      <p>
        {{ attribute(doc, 'annotation')|escape('html')|replace({'\n': "<p>"})|raw }}
      </p>
    </div>

    {#  doc.getMimeType = {{ doc.getMimeType() }};#}
    {% if is_granted('ROLE_USER') %}

      {% if doc.getMimeType() starts with 'video' %}
        <link rel="stylesheet" type="text/css" href="{{ asset('bundles/bigelibre/js/flowplayer/skin/minimalist.css') }}">
        <script type="text/javascript" src="{{ asset('bundles/bigelibre/js/flowplayer/flowplayer.min.js') }}"></script>
        <div class="flowplayer" data-adaptive-ratio="true">
          <video>
            <source type="{{ doc.getMimeType() }}" src="{{ path('big_elibre_doc', {'doc_id': doc.id,  'action' : 'download' }) }}"/>
          </video>
        </div>

        {#    <script type="text/javascript" src="{{ asset('bundles/bigelibre/js/flowplayer-flash/flowplayer-3.2.13.min.js') }}"></script>
            <a  href="{{ path('big_elibre_doc', {'doc_id': doc.id,  'action' : 'download' }) }}"
              style="display:block;width:100%;height:330px"  
              id="player"> 
            </a> 
            <script>
              flowplayer("player", "{{ asset('bundles/bigelibre/js/flowplayer-flash/flowplayer-3.2.18.swf') }}");
            </script>
        #}    
        {#    <p>
              {{ attribute(doc, 'annotation')|escape('html')|replace({'\n': "<p>"})|raw }}
            </p>#}
        {#      </div>#}

      {% endif %}
    {% endif %}
  {% endif %}
{% endblock %}

Big/ElibreBundle/Resources/views/Default/editpage.html.twig
{% extends 'BigElibreBundle:Default:index.html.twig' %}

{% block content %}
  {#<script src="{{ asset('bundles/bigelibre/js/tinymce/jquery.tinymce.min.js') }}"></script>#}
  <script src="{{ asset('bundles/bigelibre/js/tinymce/tinymce.min.js') }}"></script>

  <form action="{{ path('big_elibre_page', {'page': page, 'action': 'save'}) }}" method="post" id="EditPageForm">
    <div class="toolBox">
      <button type="submit" class="btn btn-sm btn-success"><span class="glyphicon glyphicon-floppy-save"></span> {% trans %}btn.save{% endtrans %}</button>
    </div>
    <textarea name="content" id="contentEdit">{{ content }}</textarea>
    <div class="toolBox">
      <button type="submit" class="btn btn-sm btn-success"><span class="glyphicon glyphicon-floppy-save"></span> {% trans %}btn.save{% endtrans %}</button>
    </div>
  </form>

  <script>

    tinyMCE.init({
      mode: "exact",{#    elements: "ajaxfilemanager",#}
    {#    theme: "advanced",#}
        height: 400,
        plugins: "image,media,contextmenu,filemanager",
        theme_advanced_buttons1_add_before: "newdocument,separator",
        theme_advanced_buttons1_add: "fontselect,fontsizeselect",
        theme_advanced_buttons2_add: "separator,forecolor,backcolor,liststyle",
        theme_advanced_buttons2_add_before: "cut,copy,separator,",
        theme_advanced_buttons3_add_before: "",
        theme_advanced_buttons3_add: "media",
        theme_advanced_toolbar_location: "top",
        theme_advanced_toolbar_align: "left",
        extended_valid_elements: "hr[class|width|size|noshade]",{#    file_browser_callback: ajaxfilemanager,#}
        paste_use_dialog: false,
        theme_advanced_resizing: true,
        theme_advanced_resize_horizontal: true,
        apply_source_formatting: true,
        force_br_newlines: true,
        force_p_newlines: false,
        relative_urls: true,
        selector: "textarea#contentEdit",
        language: 'ru'
      });

    {#  function ajaxfilemanager(field_name, url, type, win) {
        var ajaxfilemanagerurl = "{{ asset('bundles/bigelibre/js/tinymce/plugins/ajaxfilemanager/ajaxfilemanager.php"') }}";
        var view = 'detail';
        switch (type) {
          case "image":
            view = 'thumbnail';
            break;
          case "media":
            break;
          case "flash":
            break;
          case "file":
            break;
          default:
            return false;
        }
        ;#}
    {#    tinyMCE.activeEditor.windowManager.open({
          url: "{{ asset('bundles/bigelibre/js/tinymce/plugins/ajaxfilemanager/ajaxfilemanager.php') }}?view=" + view,
          width: 782,
          height: 440,
          inline: "yes",
          close_previous: "no"
        }, {
          window: win,
          input: field_name
        }
        );#}
    {#  }#}
  </script>

{% endblock %}

Big/ElibreBundle/Resources/views/Default/history.html.twig
{% extends 'BigElibreBundle:Default:index.html.twig' %}

{% block content %}

  
  
  &nbsp;

  {% block search_results %}
    {% if results %}
      <ul class="searchResults docList">
        {% for hdoc in results %}
          <li>
            {% if hdoc.dt is defined %}
              <div class="docDate">
                  {{ hdoc.dt|date('H:i, d.m.Y') }}
              </div>
            {% endif %}
            <a href="{{ path('big_elibre_doc', {'doc_id': hdoc.document.id,  'action' : 'view' }) }}" title="{{ attribute(hdoc.document, 'title') }}{% if hdoc.document.annotation %}<p>{% trans %}doc.annotation.label{% endtrans %}: {{ attribute(hdoc.document, 'annotation') }}</p>{% endif %}">
              {{ attribute(hdoc.document, 'title') }}
            </a>
            <span class="nowrap">
              (<a href="{{ path('big_elibre_theme', {'theme_code': hdoc.document.theme.code,  'action' : 'view' }) }}" title="{% trans %}theme.goto{% endtrans %}">{{ hdoc.document.getTheme().getTitle() }}</a>)
            </span>
            <a class="download" href="{{ path('big_elibre_doc', {'doc_id': hdoc.document.id,  'action' : 'download' }) }}" title="{% trans %}doc.download.label{% endtrans %}"><img src="{{ asset('bundles/bigelibre/images/icons/') }}{{ hdoc.document.icon }}"></a>
          </li>        
        {%endfor%}
      </ul>
    {%endif%}
  {% endblock %}  

{% endblock %}

Big/ElibreBundle/Resources/views/Default/login.html.twig
{% extends 'BigElibreBundle:Default:index.html.twig' %}

{% block content %}
<div id="LoginFormContainer">
  {% if error_msg %}
  <div class="errorMessage">{{ error_msg }}</div>
  {% endif %}

  <table>
    <form action="{{ path('login_check') }}" method="post" id="LoginForm">
      <tr>
        <td>
          <label for="username">Username:</label>
        </td>
        <td>
          <input type="text" id="username" name="_username" value="{{ last_username }}" /><br>
        </td>
      </tr>
      <tr>
        <td>
          <label for="password">Password:</label>
        </td>
        <td>
          <input type="password" id="password" name="_password" /><br>
        </td>
      </tr>
      <tr>
        <td colspan="2" class="SubmitButtons">
          <a href="{{ path('register') }}">{% trans %}Registration{% endtrans %}</a>
          <button type="submit">login</button>
        </td>
      </tr>
    </form>
  </table>
</div>
{% endblock %}

Big/ElibreBundle/Resources/views/Default/nav_menu.html.twig
{% for cur_theme in menuThemes %}
    {
      text: "{{ cur_theme.title }}",
      href: "{{ path('big_elibre_theme', {'theme_code': cur_theme.code,  'action' : 'view' }) }}",
      tags: [{% if cur_theme.getDocsCount() %}'{{ cur_theme.getDocsCount() }}'{% endif %}],
      selectable: false,
      {% if cur_theme.code == selectedTheme.code %}
      state: {
        expanded: true,
        selected: true
      },
      {% else %}
      {% endif %}
  {% if cur_theme.children.getThemesArray() %}
      nodes: [
        {% include "BigElibreBundle:Default:nav_menu.html.twig" with {'menuThemes': cur_theme.children.getThemesArray(), 'selectedTheme': selectedTheme}  %}
      ]
  {% endif %}
    },
{% endfor %}

Big/ElibreBundle/Resources/views/Default/newdocs.html.twig
{% extends 'BigElibreBundle:Default:index.html.twig' %}

{% block content %}

  &nbsp;

  {% block search_results %}
    {% if results %}
      <ul class="searchResults docList">
        {% for doc in results %}
          <li>
            {% if doc.getCreateDt() is defined %}
              <div class="docDate">
                {% block docDate %}
                  {{ doc.getCreateDt()|date('d.m.Y') }}
                {% endblock docDate %}
              </div>
            {% endif %}
            <a href="{{ path('big_elibre_doc', {'doc_id': doc.id,  'action' : 'view' }) }}" title="{{ attribute(doc, 'title') }}{% if doc.annotation %}<p>{% trans %}doc.annotation.label{% endtrans %}: {{ attribute(doc, 'annotation') }}</p>{% endif %}">
              {{ attribute(doc, 'title') }}
            </a>
            <span class="nowrap">
{#              (<a href="{{ path('big_elibre_theme', {'theme_code': doc.getTheme().getCode(),  'action' : 'view' }) }}" title="{% trans %}theme.goto{% endtrans %}">{{ doc.getTheme().getTitle() }}</a>)#}
            </span>
            <a class="download" href="{{ path('big_elibre_doc', {'doc_id': doc.id,  'action' : 'download' }) }}" title="{% trans %}doc.download.label{% endtrans %}"><img src="{{ asset('bundles/bigelibre/images/icons/') }}{{ doc.icon }}"></a>
          </li>        
        {%endfor%}
      </ul>
    {%endif%}
  {% endblock %}  

{% endblock %}

Big/ElibreBundle/Resources/views/Default/register.html.twig
{% extends 'BigElibreBundle:Default:index.html.twig' %}

{% block content %}
registration form
{% endblock %}

Big/ElibreBundle/Resources/views/Default/search.html.twig
{% extends 'BigElibreBundle:Default:index.html.twig' %}

{% block content %}

  <br>
  <center>
    <div>
      <form class="form-inline">
        <div class="input-group">
          <input type="text" name="needle" value="{{ needle }}" class="form-control border-info" placeholder="{% trans %}btn.search{% endtrans %}..." />
          <span class="input-group-btn">
            <button type="submit" class="btn btn-info" title="{% trans %}btn.search{% endtrans %}">&nbsp;<span class="glyphicon glyphicon-search"></span>&nbsp;</button>
          </span>
        </div>
      </form>
    </div>
  </center>
  <br>
  <hr>

  {% block search_results %}
    {% if results %}
      <ul class="docList">
        {% for doc in results %}
          <li>
            <a href="{{ path('big_elibre_doc', {'doc_id': doc.id,  'action' : 'view' }) }}" title="{{ attribute(doc, 'title') }}{% if doc.annotation %}<p>{% trans %}doc.annotation.label{% endtrans %}: {{ attribute(doc, 'annotation') }}</p>{% endif %}">
              {{ attribute(doc, 'title') }}
            </a>
            <a class="download" href="{{ path('big_elibre_doc', {'doc_id': doc.id,  'action' : 'download' }) }}" title="{% trans %}doc.download.label{% endtrans %}"><img src="{{ asset('bundles/bigelibre/images/icons/') }}{{ doc.icon }}"></a>
          </li>        
        {%endfor%}
      </ul>
    {%endif%}
  {% endblock %}  

{% endblock %}